<?php
/**
 * Created by PhpStorm.
 * User: 123
 * Date: 2018/9/29
 * Time: 17:23
 */
namespace app\exception;

use app\service\helper\Format;
use Exception;
use think\exception\Handle;

class ExceptionHandle extends Handle
{
    public function render(Exception $e)
    {

        //接管全局异常处理

        return Format::error($e->getMessage());

        //return parent::render($e); // TODO: Change the autogenerated stub
    }
}